version: '3'
services:
  # SQL Server: mcr.microsoft.com/mssql/server:2019-latest
  proget-sql:
    image: mssql:proget
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=L@b12345
      - MSSQL_PID=Express
    restart: unless-stopped
    volumes:
      - /proget/database:/var/opt/mssql/data
      - /proget/log:/var/opt/mssql/log
    networks:
      - proget
  # ProGet proget.inedo.com/productimages/inedo/proget:<version>
  proget:
    image: proget.inedo.com/productimages/inedo/proget:5.3.2
    environment:
      - PROGET_DB_TYPE=SqlServer
      - SQL_CONNECTION_STRING=Data Source=proget-sql;Initial Catalog=ProGet;User ID=sa;Password=L@b12345
    ports:
      - 80
    volumes:
      - /proget/packages:/var/proget/packages
      - /proget/extensions:/var/proget/extensions
    restart: unless-stopped
    networks:
      - proget
    depends_on:
      - proget-sql
# Nginx      
  nginx:
    image: nginx
    restart: unless-stopped
    environment:
      - TZ=America/Recife
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/docker01.lab.crt:/etc/ssl/private/docker01.lab.crt
      - ./certs/docker01.lab.key:/etc/ssl/private/docker01.lab.key
    depends_on:
      - proget
      - proget-sql
    networks:
      - proget

# Network      
networks:
  proget:
